FROM java:8

ADD /target/fat-microservices-pact-provider-1.0.0-SNAPSHOT.jar fat-microservices-pact-provider-1.0.0-SNAPSHOT.jar

CMD java -jar fat-microservices-pact-provider-1.0.0-SNAPSHOT.jar

EXPOSE 8080